# Generated by Django 4.0 on 2022-04-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_number_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='number',
        ),
        migrations.AddField(
            model_name='city',
            name='number',
            field=models.ManyToManyField(null=True, to='user.Number', verbose_name='Номер'),
        ),
    ]
