# Generated by Django 4.0 on 2022-04-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_city_number_city_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
