# Generated by Django 4.0 on 2022-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='number',
        ),
        migrations.AddField(
            model_name='city',
            name='numbers',
            field=models.ManyToManyField(to='contact_info.Number', verbose_name='Номер'),
        ),
    ]
